spring:
  application:
    name: met-office-mcp-server
  ai:
    mcp:
      server:
        name: met-office-mcp-server
        protocol: STREAMABLE
        type: SYNC

management:
  otlp:
    metrics:
      export:
        enabled: ${MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED:false}

met-office:
  atmospheric:
    api-key: ${MET_OFFICE_ATMOSPHERIC_API_KEY:}
    base-url: ${MET_OFFICE_ATMOSPHERIC_BASE_URL:https://data.hub.api.metoffice.gov.uk/atmospheric-models/1.0.0}
  site-specific:
    api-key: ${MET_OFFICE_SITE_SPECIFIC_API_KEY:}
    global-spot-base-url: ${MET_OFFICE_SITE_SPECIFIC_GLOBAL_SPOT_BASE_URL:https://data.hub.api.metoffice.gov.uk/sitespecific/v0/point}
    bpf-base-url: ${MET_OFFICE_SITE_SPECIFIC_BPF_BASE_URL:https://data.hub.api.metoffice.gov.uk/mo-site-specific-blended-probabilistic-forecast/1.0.0}
  observations:
    api-key: ${MET_OFFICE_OBSERVATIONS_API_KEY:}
    base-url: ${MET_OFFICE_OBSERVATIONS_BASE_URL:https://data.hub.api.metoffice.gov.uk/observation-land/1}
  map-images:
    api-key: ${MET_OFFICE_MAP_IMAGES_API_KEY:}
    base-url: ${MET_OFFICE_MAP_IMAGES_BASE_URL:https://data.hub.api.metoffice.gov.uk/map-images/1.0.0}
